env: "local" # Окружение - local, dev или prod,в первую очередь для логгера
databaseDSN: "postgres://postgres:qwerty@localhost:5432/postgres?sslmode=disable"
ServerAddress: "localhost:8080"

# type Config struct {
#     Env           string `yaml:"env" env-default:"local"`
#     ServerAddress string `json:"server_address"`
#     BaseURL       string `json:"base_url"`
#     FilePath      string `json:"file_storage_path"`
#     DatabaseDSN   string `json:"database_dsn"`
#     ConfigPath    string
# }